GET https://polar-tundra-38946.herokuapp.com/api/persons

###

DELETE https://polar-tundra-38946.herokuapp.com/api/persons/2


###

POST https://polar-tundra-38946.herokuapp.com/api/persons
content-type: application/json

{
  "name": "Test Man",
  "number": "123"
}

###